### ISSUE TITLE
Error retrieving Project IDs from CloudResourceManager

### ISSUE THREAD

**Issue by MartinHajducik** [jenkinsci/google-kubernetes-engine-plugin#80] opened 2019-05-29 13:44 UTC
Hi,

On our jenkins installation we are using proxy for plugins installation. That part is fine, plugin was installed. Then we defined Google Service account credentials based on generated .json file.

Now when we decide to use those credentials , we are getting subjected error. 

I am not sure how it work with this plugin. Does it use jenkins proxy or system proxy ? I am behind quite restrictive firewall, where we 've opened connections from Jenkins server to *.googleapis.com + accounts.google.com . But still we are unable to load ProjectIds 

I already tried to use Fiddleer to sniff traffic , but seems that this /job/gke-tracking-api-test/descriptorByName/com.google.jenkins.plugins.k8sengine.KubernetesEngineBuilder/checkCredentialsId?value=test2&credentialsId=test2 is somehow not respects plugin or environmentable jenkins server proxy settings.

How exactly this project ids are loaded from google cloud ? Or its just user browser based  action , and it depends on how user restriction level behind the firewall ?

![image](https://user-images.githubusercontent.com/41745906/58562009-b2b4b200-8228-11e9-924a-17369546c203.png)

Thank you

**Comment by stephenashank** [comment] 2019-05-29 16:31
Thanks for pointing this out, looks like the error message could be more descriptive here. I'm going to guess that if you have whitelisted those connections then the Cloud Resource Manager may need to be enabled, which can be done here: https://console.developers.google.com/apis/api/cloudresourcemanager .
If that is not the issue, this might be a permissions issue with the Google service account. Specifically, the service account must have a role that includes the permission `resourcemanager.projects.get`.

**Comment by stephenashank** [comment] 2019-05-29 22:34
Thanks for the stack trace, that's a big help. Looks like the issue is with authentication. See the Oauth2 Documentation on this interaction here: https://developers.google.com/identity/protocols/OAuth2#serviceaccount

The call that is failing is the call to get an access token and verify the credential provided, and it must connect with the Google authorization server to receive an access token. The path that you provided is actually a call made by the Jenkins web UI to the Jenkins master for form validation but the failure occurs in that external call for authentication.

**Comment by rachely3n** [comment] 2019-05-30 00:30
Did this getAccessToken issue surface when you were out of the firewall?

Also, I'm assuming you're using the permissions configurations provided in the docs? I'm going to try and replicate the error if you can provide me the permissions in your service account.

**Comment by MartinHajducik** [comment] 2019-05-31 07:14
> Did this getAccessToken issue surface when you were out of the firewall?
> 
> Also, I'm assuming you're using the permissions configurations provided in the docs? I'm going to try and replicate the error if you can provide me the permissions in your service account.

Hi

When Jenkins instance is out of firewall , all works. Seems that we just need to find all DNS server which should be whitelisted for google authentication service.

**Comment by MartinHajducik** [comment] 2019-05-31 23:03
Finally I found workaround ! it seems that Jenkins as such by default does not use/respect system proxy. So even when you define environmental variable http_proxy or https_proxy it will not work . So Manage Jenkins / manage PLugins / advanced - this proxy configuration seems to work only for plugins installation + maybe only some of the plugins are able to use it ....depends

As I am using docker for simulation of this issue in my case trick was to run jenkins using options to inject environmentable variables of http_proxy + https_proxy and **java.net.useSystemProxies=true**

![image](https://user-images.githubusercontent.com/41745906/58738935-22cd5e80-8408-11e9-8f42-f45bb6b19df5.png)

`docker run -p 8080:8080 -p 50000:50000 -e  http_proxy=http://10.0.75.1:8888/ -e https_proxy=http://10.0.75.1:8888/ --env JAVA_OPTS="-Djava.net.useSystemProxies=true" -v C:\Users\NTB\Desktop\docker\jenkins:/var/jenkins_home martinjenkins `

**Since then I was able to see in Fiddler that finally when Service Account Credentials option was selected , traffic went trough proxy and logged by Fiddler .** 

![image](https://user-images.githubusercontent.com/41745906/58738823-c0745e00-8407-11e9-9cec-66fd8938ef10.png)

Hope that this will help someone.
Martin 
- if you define environmentable variables http_proxy and https_proxy  only, you will be able to reach desired endpoints using proxy only using hosting system command line

**Comment by rachely3n** [comment] 2019-06-03 18:45
Awesome, glad it worked out. I'll be closing this, but please do re-open if further assistance is needed.

**Closed by rachely3n** 2019-06-03 18:45 UTC
